map  ba <S-Esc>
map! ba <S-Esc>
map  ca <C-Esc>
map! ca <C-Esc>
map  da <C-S-Esc>
map! da <C-S-Esc>
map  ea <A-Esc>
map! ea <A-Esc>
map  fa <A-S-Esc>
map! fa <A-S-Esc>
map  ga <A-C-Esc>
map! ga <A-C-Esc>
map  ha <A-C-S-Esc>
map! ha <A-C-S-Esc>
map  ja <D-S-Esc>
map! ja <D-S-Esc>
map  ka <D-C-Esc>
map! ka <D-C-Esc>
map  la <D-C-S-Esc>
map! la <D-C-S-Esc>
map  ma <D-A-Esc>
map! ma <D-A-Esc>
map  na <D-A-S-Esc>
map! na <D-A-S-Esc>
map  oa <D-A-C-Esc>
map! oa <D-A-C-Esc>

map  bb <S-F1>
map! bb <S-F1>
map  cb <C-F1>
map! cb <C-F1>
map  db <C-S-F1>
map! db <C-S-F1>
map  eb <A-F1>
map! eb <A-F1>
map  fb <A-S-F1>
map! fb <A-S-F1>
map  gb <A-C-F1>
map! gb <A-C-F1>
map  hb <A-C-S-F1>
map! hb <A-C-S-F1>
map  jb <D-S-F1>
map! jb <D-S-F1>
map  kb <D-C-F1>
map! kb <D-C-F1>
map  lb <D-C-S-F1>
map! lb <D-C-S-F1>
map  mb <D-A-F1>
map! mb <D-A-F1>
map  nb <D-A-S-F1>
map! nb <D-A-S-F1>
map  ob <D-A-C-F1>
map! ob <D-A-C-F1>

map  bc <S-F2>
map! bc <S-F2>
map  cc <C-F2>
map! cc <C-F2>
map  dc <C-S-F2>
map! dc <C-S-F2>
map  ec <A-F2>
map! ec <A-F2>
map  fc <A-S-F2>
map! fc <A-S-F2>
map  gc <A-C-F2>
map! gc <A-C-F2>
map  hc <A-C-S-F2>
map! hc <A-C-S-F2>
map  jc <D-S-F2>
map! jc <D-S-F2>
map  kc <D-C-F2>
map! kc <D-C-F2>
map  lc <D-C-S-F2>
map! lc <D-C-S-F2>
map  mc <D-A-F2>
map! mc <D-A-F2>
map  nc <D-A-S-F2>
map! nc <D-A-S-F2>
map  oc <D-A-C-F2>
map! oc <D-A-C-F2>

map  cd <C-F3>
map! cd <C-F3>
map  dd <C-S-F3>
map! dd <C-S-F3>
map  ed <A-F3>
map! ed <A-F3>
map  fd <A-S-F3>
map! fd <A-S-F3>
map  gd <A-C-F3>
map! gd <A-C-F3>
map  hd <A-C-S-F3>
map! hd <A-C-S-F3>
map  jd <D-S-F3>
map! jd <D-S-F3>
map  kd <D-C-F3>
map! kd <D-C-F3>
map  ld <D-C-S-F3>
map! ld <D-C-S-F3>
map  md <D-A-F3>
map! md <D-A-F3>
map  nd <D-A-S-F3>
map! nd <D-A-S-F3>
map  od <D-A-C-F3>
map! od <D-A-C-F3>

map  ce <C-F4>
map! ce <C-F4>
map  de <C-S-F4>
map! de <C-S-F4>
map  ee <A-F4>
map! ee <A-F4>
map  fe <A-S-F4>
map! fe <A-S-F4>
map  ge <A-C-F4>
map! ge <A-C-F4>
map  he <A-C-S-F4>
map! he <A-C-S-F4>
map  je <D-S-F4>
map! je <D-S-F4>
map  ke <D-C-F4>
map! ke <D-C-F4>
map  le <D-C-S-F4>
map! le <D-C-S-F4>
map  me <D-A-F4>
map! me <D-A-F4>
map  ne <D-A-S-F4>
map! ne <D-A-S-F4>
map  oe <D-A-C-F4>
map! oe <D-A-C-F4>

map  cf <C-F5>
map! cf <C-F5>
map  df <C-S-F5>
map! df <C-S-F5>
map  ef <A-F5>
map! ef <A-F5>
map  ff <A-S-F5>
map! ff <A-S-F5>
map  gf <A-C-F5>
map! gf <A-C-F5>
map  hf <A-C-S-F5>
map! hf <A-C-S-F5>
map  jf <D-S-F5>
map! jf <D-S-F5>
map  kf <D-C-F5>
map! kf <D-C-F5>
map  lf <D-C-S-F5>
map! lf <D-C-S-F5>
map  mf <D-A-F5>
map! mf <D-A-F5>
map  nf <D-A-S-F5>
map! nf <D-A-S-F5>
map  of <D-A-C-F5>
map! of <D-A-C-F5>

map  cg <C-F6>
map! cg <C-F6>
map  dg <C-S-F6>
map! dg <C-S-F6>
map  eg <A-F6>
map! eg <A-F6>
map  fg <A-S-F6>
map! fg <A-S-F6>
map  gg <A-C-F6>
map! gg <A-C-F6>
map  hg <A-C-S-F6>
map! hg <A-C-S-F6>
map  jg <D-S-F6>
map! jg <D-S-F6>
map  kg <D-C-F6>
map! kg <D-C-F6>
map  lg <D-C-S-F6>
map! lg <D-C-S-F6>
map  mg <D-A-F6>
map! mg <D-A-F6>
map  ng <D-A-S-F6>
map! ng <D-A-S-F6>
map  og <D-A-C-F6>
map! og <D-A-C-F6>

map  ch <C-F7>
map! ch <C-F7>
map  dh <C-S-F7>
map! dh <C-S-F7>
map  eh <A-F7>
map! eh <A-F7>
map  fh <A-S-F7>
map! fh <A-S-F7>
map  gh <A-C-F7>
map! gh <A-C-F7>
map  hh <A-C-S-F7>
map! hh <A-C-S-F7>
map  jh <D-S-F7>
map! jh <D-S-F7>
map  kh <D-C-F7>
map! kh <D-C-F7>
map  lh <D-C-S-F7>
map! lh <D-C-S-F7>
map  mh <D-A-F7>
map! mh <D-A-F7>
map  nh <D-A-S-F7>
map! nh <D-A-S-F7>
map  oh <D-A-C-F7>
map! oh <D-A-C-F7>

map  ci <C-F8>
map! ci <C-F8>
map  di <C-S-F8>
map! di <C-S-F8>
map  ei <A-F8>
map! ei <A-F8>
map  fi <A-S-F8>
map! fi <A-S-F8>
map  gi <A-C-F8>
map! gi <A-C-F8>
map  hi <A-C-S-F8>
map! hi <A-C-S-F8>
map  ji <D-S-F8>
map! ji <D-S-F8>
map  ki <D-C-F8>
map! ki <D-C-F8>
map  li <D-C-S-F8>
map! li <D-C-S-F8>
map  mi <D-A-F8>
map! mi <D-A-F8>
map  ni <D-A-S-F8>
map! ni <D-A-S-F8>
map  oi <D-A-C-F8>
map! oi <D-A-C-F8>

map  cj <C-F9>
map! cj <C-F9>
map  dj <C-S-F9>
map! dj <C-S-F9>
map  ej <A-F9>
map! ej <A-F9>
map  fj <A-S-F9>
map! fj <A-S-F9>
map  gj <A-C-F9>
map! gj <A-C-F9>
map  hj <A-C-S-F9>
map! hj <A-C-S-F9>
map  jj <D-S-F9>
map! jj <D-S-F9>
map  kj <D-C-F9>
map! kj <D-C-F9>
map  lj <D-C-S-F9>
map! lj <D-C-S-F9>
map  mj <D-A-F9>
map! mj <D-A-F9>
map  nj <D-A-S-F9>
map! nj <D-A-S-F9>
map  oj <D-A-C-F9>
map! oj <D-A-C-F9>

map  ck <C-F10>
map! ck <C-F10>
map  dk <C-S-F10>
map! dk <C-S-F10>
map  ek <A-F10>
map! ek <A-F10>
map  fk <A-S-F10>
map! fk <A-S-F10>
map  gk <A-C-F10>
map! gk <A-C-F10>
map  hk <A-C-S-F10>
map! hk <A-C-S-F10>
map  jk <D-S-F10>
map! jk <D-S-F10>
map  kk <D-C-F10>
map! kk <D-C-F10>
map  lk <D-C-S-F10>
map! lk <D-C-S-F10>
map  mk <D-A-F10>
map! mk <D-A-F10>
map  nk <D-A-S-F10>
map! nk <D-A-S-F10>
map  ok <D-A-C-F10>
map! ok <D-A-C-F10>

map  cl <C-F11>
map! cl <C-F11>
map  dl <C-S-F11>
map! dl <C-S-F11>
map  el <A-F11>
map! el <A-F11>
map  fl <A-S-F11>
map! fl <A-S-F11>
map  gl <A-C-F11>
map! gl <A-C-F11>
map  hl <A-C-S-F11>
map! hl <A-C-S-F11>
map  jl <D-S-F11>
map! jl <D-S-F11>
map  kl <D-C-F11>
map! kl <D-C-F11>
map  ll <D-C-S-F11>
map! ll <D-C-S-F11>
map  ml <D-A-F11>
map! ml <D-A-F11>
map  nl <D-A-S-F11>
map! nl <D-A-S-F11>
map  ol <D-A-C-F11>
map! ol <D-A-C-F11>

map  cm <C-F12>
map! cm <C-F12>
map  dm <C-S-F12>
map! dm <C-S-F12>
map  em <A-F12>
map! em <A-F12>
map  fm <A-S-F12>
map! fm <A-S-F12>
map  gm <A-C-F12>
map! gm <A-C-F12>
map  hm <A-C-S-F12>
map! hm <A-C-S-F12>
map  jm <D-S-F12>
map! jm <D-S-F12>
map  km <D-C-F12>
map! km <D-C-F12>
map  lm <D-C-S-F12>
map! lm <D-C-S-F12>
map  mm <D-A-F12>
map! mm <D-A-F12>
map  nm <D-A-S-F12>
map! nm <D-A-S-F12>
map  om <D-A-C-F12>
map! om <D-A-C-F12>

map  cn <C-`>
map! cn <C-`>
map  dn <C-S-`>
map! dn <C-S-`>
map  en <A-`>
map! en <A-`>
map  fn <A-S-`>
map! fn <A-S-`>
map  gn <A-C-`>
map! gn <A-C-`>
map  hn <A-C-S-`>
map! hn <A-C-S-`>
map  jn <D-S-`>
map! jn <D-S-`>
map  kn <D-C-`>
map! kn <D-C-`>
map  ln <D-C-S-`>
map! ln <D-C-S-`>
map  mn <D-A-`>
map! mn <D-A-`>
map  nn <D-A-S-`>
map! nn <D-A-S-`>
map  on <D-A-C-`>
map! on <D-A-C-`>

map  co <C-1>
map! co <C-1>
map  do <C-S-1>
map! do <C-S-1>
map  eo <A-1>
map! eo <A-1>
map  fo <A-S-1>
map! fo <A-S-1>
map  go <A-C-1>
map! go <A-C-1>
map  ho <A-C-S-1>
map! ho <A-C-S-1>
map  jo <D-S-1>
map! jo <D-S-1>
map  ko <D-C-1>
map! ko <D-C-1>
map  lo <D-C-S-1>
map! lo <D-C-S-1>
map  mo <D-A-1>
map! mo <D-A-1>
map  no <D-A-S-1>
map! no <D-A-S-1>
map  oo <D-A-C-1>
map! oo <D-A-C-1>

map  cp <C-2>
map! cp <C-2>
map  dp <C-S-2>
map! dp <C-S-2>
map  ep <A-2>
map! ep <A-2>
map  fp <A-S-2>
map! fp <A-S-2>
map  gp <A-C-2>
map! gp <A-C-2>
map  hp <A-C-S-2>
map! hp <A-C-S-2>
map  jp <D-S-2>
map! jp <D-S-2>
map  kp <D-C-2>
map! kp <D-C-2>
map  lp <D-C-S-2>
map! lp <D-C-S-2>
map  mp <D-A-2>
map! mp <D-A-2>
map  np <D-A-S-2>
map! np <D-A-S-2>
map  op <D-A-C-2>
map! op <D-A-C-2>

map  cq <C-3>
map! cq <C-3>
map  dq <C-S-3>
map! dq <C-S-3>
map  eq <A-3>
map! eq <A-3>
map  fq <A-S-3>
map! fq <A-S-3>
map  gq <A-C-3>
map! gq <A-C-3>
map  hq <A-C-S-3>
map! hq <A-C-S-3>
map  jq <D-S-3>
map! jq <D-S-3>
map  kq <D-C-3>
map! kq <D-C-3>
map  lq <D-C-S-3>
map! lq <D-C-S-3>
map  mq <D-A-3>
map! mq <D-A-3>
map  nq <D-A-S-3>
map! nq <D-A-S-3>
map  oq <D-A-C-3>
map! oq <D-A-C-3>

map  cr <C-4>
map! cr <C-4>
map  dr <C-S-4>
map! dr <C-S-4>
map  er <A-4>
map! er <A-4>
map  fr <A-S-4>
map! fr <A-S-4>
map  gr <A-C-4>
map! gr <A-C-4>
map  hr <A-C-S-4>
map! hr <A-C-S-4>
map  jr <D-S-4>
map! jr <D-S-4>
map  kr <D-C-4>
map! kr <D-C-4>
map  lr <D-C-S-4>
map! lr <D-C-S-4>
map  mr <D-A-4>
map! mr <D-A-4>
map  nr <D-A-S-4>
map! nr <D-A-S-4>
map  or <D-A-C-4>
map! or <D-A-C-4>

map  cs <C-5>
map! cs <C-5>
map  ds <C-S-5>
map! ds <C-S-5>
map  es <A-5>
map! es <A-5>
map  fs <A-S-5>
map! fs <A-S-5>
map  gs <A-C-5>
map! gs <A-C-5>
map  hs <A-C-S-5>
map! hs <A-C-S-5>
map  js <D-S-5>
map! js <D-S-5>
map  ks <D-C-5>
map! ks <D-C-5>
map  ls <D-C-S-5>
map! ls <D-C-S-5>
map  ms <D-A-5>
map! ms <D-A-5>
map  ns <D-A-S-5>
map! ns <D-A-S-5>
map  os <D-A-C-5>
map! os <D-A-C-5>

map  dt <C-S-6>
map! dt <C-S-6>
map  et <A-6>
map! et <A-6>
map  ft <A-S-6>
map! ft <A-S-6>
map  gt <A-C-6>
map! gt <A-C-6>
map  ht <A-C-S-6>
map! ht <A-C-S-6>
map  jt <D-S-6>
map! jt <D-S-6>
map  kt <D-C-6>
map! kt <D-C-6>
map  lt <D-C-S-6>
map! lt <D-C-S-6>
map  mt <D-A-6>
map! mt <D-A-6>
map  nt <D-A-S-6>
map! nt <D-A-S-6>
map  ot <D-A-C-6>
map! ot <D-A-C-6>

map  cu <C-7>
map! cu <C-7>
map  du <C-S-7>
map! du <C-S-7>
map  eu <A-7>
map! eu <A-7>
map  fu <A-S-7>
map! fu <A-S-7>
map  gu <A-C-7>
map! gu <A-C-7>
map  hu <A-C-S-7>
map! hu <A-C-S-7>
map  ju <D-S-7>
map! ju <D-S-7>
map  ku <D-C-7>
map! ku <D-C-7>
map  lu <D-C-S-7>
map! lu <D-C-S-7>
map  mu <D-A-7>
map! mu <D-A-7>
map  nu <D-A-S-7>
map! nu <D-A-S-7>
map  ou <D-A-C-7>
map! ou <D-A-C-7>

map  cv <C-8>
map! cv <C-8>
map  dv <C-S-8>
map! dv <C-S-8>
map  ev <A-8>
map! ev <A-8>
map  fv <A-S-8>
map! fv <A-S-8>
map  gv <A-C-8>
map! gv <A-C-8>
map  hv <A-C-S-8>
map! hv <A-C-S-8>
map  jv <D-S-8>
map! jv <D-S-8>
map  kv <D-C-8>
map! kv <D-C-8>
map  lv <D-C-S-8>
map! lv <D-C-S-8>
map  mv <D-A-8>
map! mv <D-A-8>
map  nv <D-A-S-8>
map! nv <D-A-S-8>
map  ov <D-A-C-8>
map! ov <D-A-C-8>

map  cw <C-9>
map! cw <C-9>
map  dw <C-S-9>
map! dw <C-S-9>
map  ew <A-9>
map! ew <A-9>
map  fw <A-S-9>
map! fw <A-S-9>
map  gw <A-C-9>
map! gw <A-C-9>
map  hw <A-C-S-9>
map! hw <A-C-S-9>
map  jw <D-S-9>
map! jw <D-S-9>
map  kw <D-C-9>
map! kw <D-C-9>
map  lw <D-C-S-9>
map! lw <D-C-S-9>
map  mw <D-A-9>
map! mw <D-A-9>
map  nw <D-A-S-9>
map! nw <D-A-S-9>
map  ow <D-A-C-9>
map! ow <D-A-C-9>

map  cx <C-0>
map! cx <C-0>
map  dx <C-S-0>
map! dx <C-S-0>
map  ex <A-0>
map! ex <A-0>
map  fx <A-S-0>
map! fx <A-S-0>
map  gx <A-C-0>
map! gx <A-C-0>
map  hx <A-C-S-0>
map! hx <A-C-S-0>
map  jx <D-S-0>
map! jx <D-S-0>
map  kx <D-C-0>
map! kx <D-C-0>
map  lx <D-C-S-0>
map! lx <D-C-S-0>
map  mx <D-A-0>
map! mx <D-A-0>
map  nx <D-A-S-0>
map! nx <D-A-S-0>
map  ox <D-A-C-0>
map! ox <D-A-C-0>

map  dy <C-S-->
map! dy <C-S-->
map  ey <A-->
map! ey <A-->
map  fy <A-S-->
map! fy <A-S-->
map  gy <A-C-->
map! gy <A-C-->
map  hy <A-C-S-->
map! hy <A-C-S-->
map  jy <D-S-->
map! jy <D-S-->
map  ky <D-C-->
map! ky <D-C-->
map  ly <D-C-S-->
map! ly <D-C-S-->
map  my <D-A-->
map! my <D-A-->
map  ny <D-A-S-->
map! ny <D-A-S-->
map  oy <D-A-C-->
map! oy <D-A-C-->

map  cz <C-=>
map! cz <C-=>
map  dz <C-S-=>
map! dz <C-S-=>
map  ez <A-=>
map! ez <A-=>
map  fz <A-S-=>
map! fz <A-S-=>
map  gz <A-C-=>
map! gz <A-C-=>
map  hz <A-C-S-=>
map! hz <A-C-S-=>
map  jz <D-S-=>
map! jz <D-S-=>
map  kz <D-C-=>
map! kz <D-C-=>
map  lz <D-C-S-=>
map! lz <D-C-S-=>
map  mz <D-A-=>
map! mz <D-A-=>
map  nz <D-A-S-=>
map! nz <D-A-S-=>
map  oz <D-A-C-=>
map! oz <D-A-C-=>

map  bba <S-BS>
map! bba <S-BS>
map  cba <C-BS>
map! cba <C-BS>
map  dba <C-S-BS>
map! dba <C-S-BS>
map  eba <A-BS>
map! eba <A-BS>
map  fba <A-S-BS>
map! fba <A-S-BS>
map  gba <A-C-BS>
map! gba <A-C-BS>
map  hba <A-C-S-BS>
map! hba <A-C-S-BS>
map  jba <D-S-BS>
map! jba <D-S-BS>
map  kba <D-C-BS>
map! kba <D-C-BS>
map  lba <D-C-S-BS>
map! lba <D-C-S-BS>
map  mba <D-A-BS>
map! mba <D-A-BS>
map  nba <D-A-S-BS>
map! nba <D-A-S-BS>
map  oba <D-A-C-BS>
map! oba <D-A-C-BS>

map  cbb <C-Tab>
map! cbb <C-Tab>
map  dbb <C-S-Tab>
map! dbb <C-S-Tab>
map  ebb <A-Tab>
map! ebb <A-Tab>
map  fbb <A-S-Tab>
map! fbb <A-S-Tab>
map  gbb <A-C-Tab>
map! gbb <A-C-Tab>
map  hbb <A-C-S-Tab>
map! hbb <A-C-S-Tab>
map  jbb <D-S-Tab>
map! jbb <D-S-Tab>
map  kbb <D-C-Tab>
map! kbb <D-C-Tab>
map  lbb <D-C-S-Tab>
map! lbb <D-C-S-Tab>
map  mbb <D-A-Tab>
map! mbb <D-A-Tab>
map  nbb <D-A-S-Tab>
map! nbb <D-A-S-Tab>
map  obb <D-A-C-Tab>
map! obb <D-A-C-Tab>

map  dbc <C-S-q>
map! dbc <C-S-q>
map  ebc <A-q>
map! ebc <A-q>
map  fbc <A-S-q>
map! fbc <A-S-q>
map  gbc <A-C-q>
map! gbc <A-C-q>
map  hbc <A-C-S-q>
map! hbc <A-C-S-q>
map  jbc <D-S-q>
map! jbc <D-S-q>
map  kbc <D-C-q>
map! kbc <D-C-q>
map  lbc <D-C-S-q>
map! lbc <D-C-S-q>
map  mbc <D-A-q>
map! mbc <D-A-q>
map  nbc <D-A-S-q>
map! nbc <D-A-S-q>
map  obc <D-A-C-q>
map! obc <D-A-C-q>

map  dbd <C-S-w>
map! dbd <C-S-w>
map  ebd <A-w>
map! ebd <A-w>
map  fbd <A-S-w>
map! fbd <A-S-w>
map  gbd <A-C-w>
map! gbd <A-C-w>
map  hbd <A-C-S-w>
map! hbd <A-C-S-w>
map  jbd <D-S-w>
map! jbd <D-S-w>
map  kbd <D-C-w>
map! kbd <D-C-w>
map  lbd <D-C-S-w>
map! lbd <D-C-S-w>
map  mbd <D-A-w>
map! mbd <D-A-w>
map  nbd <D-A-S-w>
map! nbd <D-A-S-w>
map  obd <D-A-C-w>
map! obd <D-A-C-w>

map  dbe <C-S-e>
map! dbe <C-S-e>
map  ebe <A-e>
map! ebe <A-e>
map  fbe <A-S-e>
map! fbe <A-S-e>
map  gbe <A-C-e>
map! gbe <A-C-e>
map  hbe <A-C-S-e>
map! hbe <A-C-S-e>
map  jbe <D-S-e>
map! jbe <D-S-e>
map  kbe <D-C-e>
map! kbe <D-C-e>
map  lbe <D-C-S-e>
map! lbe <D-C-S-e>
map  mbe <D-A-e>
map! mbe <D-A-e>
map  nbe <D-A-S-e>
map! nbe <D-A-S-e>
map  obe <D-A-C-e>
map! obe <D-A-C-e>

map  dbf <C-S-r>
map! dbf <C-S-r>
map  ebf <A-r>
map! ebf <A-r>
map  fbf <A-S-r>
map! fbf <A-S-r>
map  gbf <A-C-r>
map! gbf <A-C-r>
map  hbf <A-C-S-r>
map! hbf <A-C-S-r>
map  jbf <D-S-r>
map! jbf <D-S-r>
map  kbf <D-C-r>
map! kbf <D-C-r>
map  lbf <D-C-S-r>
map! lbf <D-C-S-r>
map  mbf <D-A-r>
map! mbf <D-A-r>
map  nbf <D-A-S-r>
map! nbf <D-A-S-r>
map  obf <D-A-C-r>
map! obf <D-A-C-r>

map  dbg <C-S-t>
map! dbg <C-S-t>
map  ebg <A-t>
map! ebg <A-t>
map  fbg <A-S-t>
map! fbg <A-S-t>
map  gbg <A-C-t>
map! gbg <A-C-t>
map  hbg <A-C-S-t>
map! hbg <A-C-S-t>
map  jbg <D-S-t>
map! jbg <D-S-t>
map  kbg <D-C-t>
map! kbg <D-C-t>
map  lbg <D-C-S-t>
map! lbg <D-C-S-t>
map  mbg <D-A-t>
map! mbg <D-A-t>
map  nbg <D-A-S-t>
map! nbg <D-A-S-t>
map  obg <D-A-C-t>
map! obg <D-A-C-t>

map  dbh <C-S-y>
map! dbh <C-S-y>
map  ebh <A-y>
map! ebh <A-y>
map  fbh <A-S-y>
map! fbh <A-S-y>
map  gbh <A-C-y>
map! gbh <A-C-y>
map  hbh <A-C-S-y>
map! hbh <A-C-S-y>
map  jbh <D-S-y>
map! jbh <D-S-y>
map  kbh <D-C-y>
map! kbh <D-C-y>
map  lbh <D-C-S-y>
map! lbh <D-C-S-y>
map  mbh <D-A-y>
map! mbh <D-A-y>
map  nbh <D-A-S-y>
map! nbh <D-A-S-y>
map  obh <D-A-C-y>
map! obh <D-A-C-y>

map  dbi <C-S-u>
map! dbi <C-S-u>
map  ebi <A-u>
map! ebi <A-u>
map  fbi <A-S-u>
map! fbi <A-S-u>
map  gbi <A-C-u>
map! gbi <A-C-u>
map  hbi <A-C-S-u>
map! hbi <A-C-S-u>
map  jbi <D-S-u>
map! jbi <D-S-u>
map  kbi <D-C-u>
map! kbi <D-C-u>
map  lbi <D-C-S-u>
map! lbi <D-C-S-u>
map  mbi <D-A-u>
map! mbi <D-A-u>
map  nbi <D-A-S-u>
map! nbi <D-A-S-u>
map  obi <D-A-C-u>
map! obi <D-A-C-u>

map  dbj <C-S-i>
map! dbj <C-S-i>
map  ebj <A-i>
map! ebj <A-i>
map  fbj <A-S-i>
map! fbj <A-S-i>
map  gbj <A-C-i>
map! gbj <A-C-i>
map  hbj <A-C-S-i>
map! hbj <A-C-S-i>
map  jbj <D-S-i>
map! jbj <D-S-i>
map  kbj <D-C-i>
map! kbj <D-C-i>
map  lbj <D-C-S-i>
map! lbj <D-C-S-i>
map  mbj <D-A-i>
map! mbj <D-A-i>
map  nbj <D-A-S-i>
map! nbj <D-A-S-i>
map  obj <D-A-C-i>
map! obj <D-A-C-i>
map  qbj <CTRL-i>
map! qbj <CTRL-i>

map  dbk <C-S-o>
map! dbk <C-S-o>
map  ebk <A-o>
map! ebk <A-o>
map  fbk <A-S-o>
map! fbk <A-S-o>
map  gbk <A-C-o>
map! gbk <A-C-o>
map  hbk <A-C-S-o>
map! hbk <A-C-S-o>
map  jbk <D-S-o>
map! jbk <D-S-o>
map  kbk <D-C-o>
map! kbk <D-C-o>
map  lbk <D-C-S-o>
map! lbk <D-C-S-o>
map  mbk <D-A-o>
map! mbk <D-A-o>
map  nbk <D-A-S-o>
map! nbk <D-A-S-o>
map  obk <D-A-C-o>
map! obk <D-A-C-o>

map  dbl <C-S-p>
map! dbl <C-S-p>
map  ebl <A-p>
map! ebl <A-p>
map  fbl <A-S-p>
map! fbl <A-S-p>
map  gbl <A-C-p>
map! gbl <A-C-p>
map  hbl <A-C-S-p>
map! hbl <A-C-S-p>
map  jbl <D-S-p>
map! jbl <D-S-p>
map  kbl <D-C-p>
map! kbl <D-C-p>
map  lbl <D-C-S-p>
map! lbl <D-C-S-p>
map  mbl <D-A-p>
map! mbl <D-A-p>
map  nbl <D-A-S-p>
map! nbl <D-A-S-p>
map  obl <D-A-C-p>
map! obl <D-A-C-p>

map  cbm <C-[>
map! cbm <C-[>
map  dbm <C-S-[>
map! dbm <C-S-[>
map  ebm <A-[>
map! ebm <A-[>
map  fbm <A-S-[>
map! fbm <A-S-[>
map  gbm <A-C-[>
map! gbm <A-C-[>
map  hbm <A-C-S-[>
map! hbm <A-C-S-[>
map  jbm <D-S-[>
map! jbm <D-S-[>
map  kbm <D-C-[>
map! kbm <D-C-[>
map  lbm <D-C-S-[>
map! lbm <D-C-S-[>
map  mbm <D-A-[>
map! mbm <D-A-[>
map  nbm <D-A-S-[>
map! nbm <D-A-S-[>
map  obm <D-A-C-[>
map! obm <D-A-C-[>

map  dbn <C-S-]>
map! dbn <C-S-]>
map  ebn <A-]>
map! ebn <A-]>
map  fbn <A-S-]>
map! fbn <A-S-]>
map  gbn <A-C-]>
map! gbn <A-C-]>
map  hbn <A-C-S-]>
map! hbn <A-C-S-]>
map  jbn <D-S-]>
map! jbn <D-S-]>
map  kbn <D-C-]>
map! kbn <D-C-]>
map  lbn <D-C-S-]>
map! lbn <D-C-S-]>
map  mbn <D-A-]>
map! mbn <D-A-]>
map  nbn <D-A-S-]>
map! nbn <D-A-S-]>
map  obn <D-A-C-]>
map! obn <D-A-C-]>

map  bbo <S-CR>
map! bbo <S-CR>
map  cbo <C-CR>
map! cbo <C-CR>
map  dbo <C-S-CR>
map! dbo <C-S-CR>
map  ebo <A-CR>
map! ebo <A-CR>
map  fbo <A-S-CR>
map! fbo <A-S-CR>
map  gbo <A-C-CR>
map! gbo <A-C-CR>
map  hbo <A-C-S-CR>
map! hbo <A-C-S-CR>
map  jbo <D-S-CR>
map! jbo <D-S-CR>
map  kbo <D-C-CR>
map! kbo <D-C-CR>
map  lbo <D-C-S-CR>
map! lbo <D-C-S-CR>
map  mbo <D-A-CR>
map! mbo <D-A-CR>
map  nbo <D-A-S-CR>
map! nbo <D-A-S-CR>
map  obo <D-A-C-CR>
map! obo <D-A-C-CR>

map  dbp <C-S-a>
map! dbp <C-S-a>
map  ebp <A-a>
map! ebp <A-a>
map  fbp <A-S-a>
map! fbp <A-S-a>
map  gbp <A-C-a>
map! gbp <A-C-a>
map  hbp <A-C-S-a>
map! hbp <A-C-S-a>
map  jbp <D-S-a>
map! jbp <D-S-a>
map  kbp <D-C-a>
map! kbp <D-C-a>
map  lbp <D-C-S-a>
map! lbp <D-C-S-a>
map  mbp <D-A-a>
map! mbp <D-A-a>
map  nbp <D-A-S-a>
map! nbp <D-A-S-a>
map  obp <D-A-C-a>
map! obp <D-A-C-a>

map  dbq <C-S-s>
map! dbq <C-S-s>
map  ebq <A-s>
map! ebq <A-s>
map  fbq <A-S-s>
map! fbq <A-S-s>
map  gbq <A-C-s>
map! gbq <A-C-s>
map  hbq <A-C-S-s>
map! hbq <A-C-S-s>
map  jbq <D-S-s>
map! jbq <D-S-s>
map  kbq <D-C-s>
map! kbq <D-C-s>
map  lbq <D-C-S-s>
map! lbq <D-C-S-s>
map  mbq <D-A-s>
map! mbq <D-A-s>
map  nbq <D-A-S-s>
map! nbq <D-A-S-s>
map  obq <D-A-C-s>
map! obq <D-A-C-s>

map  dbr <C-S-d>
map! dbr <C-S-d>
map  ebr <A-d>
map! ebr <A-d>
map  fbr <A-S-d>
map! fbr <A-S-d>
map  gbr <A-C-d>
map! gbr <A-C-d>
map  hbr <A-C-S-d>
map! hbr <A-C-S-d>
map  jbr <D-S-d>
map! jbr <D-S-d>
map  kbr <D-C-d>
map! kbr <D-C-d>
map  lbr <D-C-S-d>
map! lbr <D-C-S-d>
map  mbr <D-A-d>
map! mbr <D-A-d>
map  nbr <D-A-S-d>
map! nbr <D-A-S-d>
map  obr <D-A-C-d>
map! obr <D-A-C-d>

map  dbs <C-S-f>
map! dbs <C-S-f>
map  ebs <A-f>
map! ebs <A-f>
map  fbs <A-S-f>
map! fbs <A-S-f>
map  gbs <A-C-f>
map! gbs <A-C-f>
map  hbs <A-C-S-f>
map! hbs <A-C-S-f>
map  jbs <D-S-f>
map! jbs <D-S-f>
map  kbs <D-C-f>
map! kbs <D-C-f>
map  lbs <D-C-S-f>
map! lbs <D-C-S-f>
map  mbs <D-A-f>
map! mbs <D-A-f>
map  nbs <D-A-S-f>
map! nbs <D-A-S-f>
map  obs <D-A-C-f>
map! obs <D-A-C-f>

map  dbt <C-S-g>
map! dbt <C-S-g>
map  ebt <A-g>
map! ebt <A-g>
map  fbt <A-S-g>
map! fbt <A-S-g>
map  gbt <A-C-g>
map! gbt <A-C-g>
map  hbt <A-C-S-g>
map! hbt <A-C-S-g>
map  jbt <D-S-g>
map! jbt <D-S-g>
map  kbt <D-C-g>
map! kbt <D-C-g>
map  lbt <D-C-S-g>
map! lbt <D-C-S-g>
map  mbt <D-A-g>
map! mbt <D-A-g>
map  nbt <D-A-S-g>
map! nbt <D-A-S-g>
map  obt <D-A-C-g>
map! obt <D-A-C-g>

map  dbu <C-S-h>
map! dbu <C-S-h>
map  ebu <A-h>
map! ebu <A-h>
map  fbu <A-S-h>
map! fbu <A-S-h>
map  gbu <A-C-h>
map! gbu <A-C-h>
map  hbu <A-C-S-h>
map! hbu <A-C-S-h>
map  jbu <D-S-h>
map! jbu <D-S-h>
map  kbu <D-C-h>
map! kbu <D-C-h>
map  lbu <D-C-S-h>
map! lbu <D-C-S-h>
map  mbu <D-A-h>
map! mbu <D-A-h>
map  nbu <D-A-S-h>
map! nbu <D-A-S-h>
map  obu <D-A-C-h>
map! obu <D-A-C-h>
map  qbu <CTRL-h>
map! qbu <CTRL-h>

map  dbv <C-S-j>
map! dbv <C-S-j>
map  ebv <A-j>
map! ebv <A-j>
map  fbv <A-S-j>
map! fbv <A-S-j>
map  gbv <A-C-j>
map! gbv <A-C-j>
map  hbv <A-C-S-j>
map! hbv <A-C-S-j>
map  jbv <D-S-j>
map! jbv <D-S-j>
map  kbv <D-C-j>
map! kbv <D-C-j>
map  lbv <D-C-S-j>
map! lbv <D-C-S-j>
map  mbv <D-A-j>
map! mbv <D-A-j>
map  nbv <D-A-S-j>
map! nbv <D-A-S-j>
map  obv <D-A-C-j>
map! obv <D-A-C-j>

map  dbw <C-S-k>
map! dbw <C-S-k>
map  ebw <A-k>
map! ebw <A-k>
map  fbw <A-S-k>
map! fbw <A-S-k>
map  gbw <A-C-k>
map! gbw <A-C-k>
map  hbw <A-C-S-k>
map! hbw <A-C-S-k>
map  jbw <D-S-k>
map! jbw <D-S-k>
map  kbw <D-C-k>
map! kbw <D-C-k>
map  lbw <D-C-S-k>
map! lbw <D-C-S-k>
map  mbw <D-A-k>
map! mbw <D-A-k>
map  nbw <D-A-S-k>
map! nbw <D-A-S-k>
map  obw <D-A-C-k>
map! obw <D-A-C-k>

map  dbx <C-S-l>
map! dbx <C-S-l>
map  ebx <A-l>
map! ebx <A-l>
map  fbx <A-S-l>
map! fbx <A-S-l>
map  gbx <A-C-l>
map! gbx <A-C-l>
map  hbx <A-C-S-l>
map! hbx <A-C-S-l>
map  jbx <D-S-l>
map! jbx <D-S-l>
map  kbx <D-C-l>
map! kbx <D-C-l>
map  lbx <D-C-S-l>
map! lbx <D-C-S-l>
map  mbx <D-A-l>
map! mbx <D-A-l>
map  nbx <D-A-S-l>
map! nbx <D-A-S-l>
map  obx <D-A-C-l>
map! obx <D-A-C-l>

map  cby <C-;>
map! cby <C-;>
map  dby <C-S-;>
map! dby <C-S-;>
map  eby <A-;>
map! eby <A-;>
map  fby <A-S-;>
map! fby <A-S-;>
map  gby <A-C-;>
map! gby <A-C-;>
map  hby <A-C-S-;>
map! hby <A-C-S-;>
map  jby <D-S-;>
map! jby <D-S-;>
map  kby <D-C-;>
map! kby <D-C-;>
map  lby <D-C-S-;>
map! lby <D-C-S-;>
map  mby <D-A-;>
map! mby <D-A-;>
map  nby <D-A-S-;>
map! nby <D-A-S-;>
map  oby <D-A-C-;>
map! oby <D-A-C-;>

map  cbz <C-'>
map! cbz <C-'>
map  dbz <C-S-'>
map! dbz <C-S-'>
map  ebz <A-'>
map! ebz <A-'>
map  fbz <A-S-'>
map! fbz <A-S-'>
map  gbz <A-C-'>
map! gbz <A-C-'>
map  hbz <A-C-S-'>
map! hbz <A-C-S-'>
map  jbz <D-S-'>
map! jbz <D-S-'>
map  kbz <D-C-'>
map! kbz <D-C-'>
map  lbz <D-C-S-'>
map! lbz <D-C-S-'>
map  mbz <D-A-'>
map! mbz <D-A-'>
map  nbz <D-A-S-'>
map! nbz <D-A-S-'>
map  obz <D-A-C-'>
map! obz <D-A-C-'>

map  dca <C-S-Bslash>
map! dca <C-S-Bslash>
map  eca <A-Bslash>
map! eca <A-Bslash>
map  fca <A-S-Bslash>
map! fca <A-S-Bslash>
map  gca <A-C-Bslash>
map! gca <A-C-Bslash>
map  hca <A-C-S-Bslash>
map! hca <A-C-S-Bslash>
map  jca <D-S-Bslash>
map! jca <D-S-Bslash>
map  kca <D-C-Bslash>
map! kca <D-C-Bslash>
map  lca <D-C-S-Bslash>
map! lca <D-C-S-Bslash>
map  mca <D-A-Bslash>
map! mca <D-A-Bslash>
map  nca <D-A-S-Bslash>
map! nca <D-A-S-Bslash>
map  oca <D-A-C-Bslash>
map! oca <D-A-C-Bslash>

map  dcb <C-S-z>
map! dcb <C-S-z>
map  ecb <A-z>
map! ecb <A-z>
map  fcb <A-S-z>
map! fcb <A-S-z>
map  gcb <A-C-z>
map! gcb <A-C-z>
map  hcb <A-C-S-z>
map! hcb <A-C-S-z>
map  jcb <D-S-z>
map! jcb <D-S-z>
map  kcb <D-C-z>
map! kcb <D-C-z>
map  lcb <D-C-S-z>
map! lcb <D-C-S-z>
map  mcb <D-A-z>
map! mcb <D-A-z>
map  ncb <D-A-S-z>
map! ncb <D-A-S-z>
map  ocb <D-A-C-z>
map! ocb <D-A-C-z>

map  dcc <C-S-x>
map! dcc <C-S-x>
map  ecc <A-x>
map! ecc <A-x>
map  fcc <A-S-x>
map! fcc <A-S-x>
map  gcc <A-C-x>
map! gcc <A-C-x>
map  hcc <A-C-S-x>
map! hcc <A-C-S-x>
map  jcc <D-S-x>
map! jcc <D-S-x>
map  kcc <D-C-x>
map! kcc <D-C-x>
map  lcc <D-C-S-x>
map! lcc <D-C-S-x>
map  mcc <D-A-x>
map! mcc <D-A-x>
map  ncc <D-A-S-x>
map! ncc <D-A-S-x>
map  occ <D-A-C-x>
map! occ <D-A-C-x>

map  dcd <C-S-c>
map! dcd <C-S-c>
map  ecd <A-c>
map! ecd <A-c>
map  fcd <A-S-c>
map! fcd <A-S-c>
map  gcd <A-C-c>
map! gcd <A-C-c>
map  hcd <A-C-S-c>
map! hcd <A-C-S-c>
map  jcd <D-S-c>
map! jcd <D-S-c>
map  kcd <D-C-c>
map! kcd <D-C-c>
map  lcd <D-C-S-c>
map! lcd <D-C-S-c>
map  mcd <D-A-c>
map! mcd <D-A-c>
map  ncd <D-A-S-c>
map! ncd <D-A-S-c>
map  ocd <D-A-C-c>
map! ocd <D-A-C-c>

map  dce <C-S-v>
map! dce <C-S-v>
map  ece <A-v>
map! ece <A-v>
map  fce <A-S-v>
map! fce <A-S-v>
map  gce <A-C-v>
map! gce <A-C-v>
map  hce <A-C-S-v>
map! hce <A-C-S-v>
map  jce <D-S-v>
map! jce <D-S-v>
map  kce <D-C-v>
map! kce <D-C-v>
map  lce <D-C-S-v>
map! lce <D-C-S-v>
map  mce <D-A-v>
map! mce <D-A-v>
map  nce <D-A-S-v>
map! nce <D-A-S-v>
map  oce <D-A-C-v>
map! oce <D-A-C-v>

map  dcf <C-S-b>
map! dcf <C-S-b>
map  ecf <A-b>
map! ecf <A-b>
map  fcf <A-S-b>
map! fcf <A-S-b>
map  gcf <A-C-b>
map! gcf <A-C-b>
map  hcf <A-C-S-b>
map! hcf <A-C-S-b>
map  jcf <D-S-b>
map! jcf <D-S-b>
map  kcf <D-C-b>
map! kcf <D-C-b>
map  lcf <D-C-S-b>
map! lcf <D-C-S-b>
map  mcf <D-A-b>
map! mcf <D-A-b>
map  ncf <D-A-S-b>
map! ncf <D-A-S-b>
map  ocf <D-A-C-b>
map! ocf <D-A-C-b>

map  dcg <C-S-n>
map! dcg <C-S-n>
map  ecg <A-n>
map! ecg <A-n>
map  fcg <A-S-n>
map! fcg <A-S-n>
map  gcg <A-C-n>
map! gcg <A-C-n>
map  hcg <A-C-S-n>
map! hcg <A-C-S-n>
map  jcg <D-S-n>
map! jcg <D-S-n>
map  kcg <D-C-n>
map! kcg <D-C-n>
map  lcg <D-C-S-n>
map! lcg <D-C-S-n>
map  mcg <D-A-n>
map! mcg <D-A-n>
map  ncg <D-A-S-n>
map! ncg <D-A-S-n>
map  ocg <D-A-C-n>
map! ocg <D-A-C-n>

map  dch <C-S-m>
map! dch <C-S-m>
map  ech <A-m>
map! ech <A-m>
map  fch <A-S-m>
map! fch <A-S-m>
map  gch <A-C-m>
map! gch <A-C-m>
map  hch <A-C-S-m>
map! hch <A-C-S-m>
map  jch <D-S-m>
map! jch <D-S-m>
map  kch <D-C-m>
map! kch <D-C-m>
map  lch <D-C-S-m>
map! lch <D-C-S-m>
map  mch <D-A-m>
map! mch <D-A-m>
map  nch <D-A-S-m>
map! nch <D-A-S-m>
map  och <D-A-C-m>
map! och <D-A-C-m>
map  qch <CTRL-m>
map! qch <CTRL-m>

map  cci <C-,>
map! cci <C-,>
map  dci <C-S-,>
map! dci <C-S-,>
map  eci <A-,>
map! eci <A-,>
map  fci <A-S-,>
map! fci <A-S-,>
map  gci <A-C-,>
map! gci <A-C-,>
map  hci <A-C-S-,>
map! hci <A-C-S-,>
map  jci <D-S-,>
map! jci <D-S-,>
map  kci <D-C-,>
map! kci <D-C-,>
map  lci <D-C-S-,>
map! lci <D-C-S-,>
map  mci <D-A-,>
map! mci <D-A-,>
map  nci <D-A-S-,>
map! nci <D-A-S-,>
map  oci <D-A-C-,>
map! oci <D-A-C-,>

map  ccj <C-.>
map! ccj <C-.>
map  dcj <C-S-.>
map! dcj <C-S-.>
map  ecj <A-.>
map! ecj <A-.>
map  fcj <A-S-.>
map! fcj <A-S-.>
map  gcj <A-C-.>
map! gcj <A-C-.>
map  hcj <A-C-S-.>
map! hcj <A-C-S-.>
map  jcj <D-S-.>
map! jcj <D-S-.>
map  kcj <D-C-.>
map! kcj <D-C-.>
map  lcj <D-C-S-.>
map! lcj <D-C-S-.>
map  mcj <D-A-.>
map! mcj <D-A-.>
map  ncj <D-A-S-.>
map! ncj <D-A-S-.>
map  ocj <D-A-C-.>
map! ocj <D-A-C-.>

map  cck <C-/>
map! cck <C-/>
map  dck <C-S-/>
map! dck <C-S-/>
map  eck <A-/>
map! eck <A-/>
map  fck <A-S-/>
map! fck <A-S-/>
map  gck <A-C-/>
map! gck <A-C-/>
map  hck <A-C-S-/>
map! hck <A-C-S-/>
map  jck <D-S-/>
map! jck <D-S-/>
map  kck <D-C-/>
map! kck <D-C-/>
map  lck <D-C-S-/>
map! lck <D-C-S-/>
map  mck <D-A-/>
map! mck <D-A-/>
map  nck <D-A-S-/>
map! nck <D-A-S-/>
map  ock <D-A-C-/>
map! ock <D-A-C-/>

map  bcl <S-Space>
map! bcl <S-Space>
map  ccl <C-Space>
map! ccl <C-Space>
map  dcl <C-S-Space>
map! dcl <C-S-Space>
map  ecl <A-Space>
map! ecl <A-Space>
map  fcl <A-S-Space>
map! fcl <A-S-Space>
map  gcl <A-C-Space>
map! gcl <A-C-Space>
map  hcl <A-C-S-Space>
map! hcl <A-C-S-Space>
map  jcl <D-S-Space>
map! jcl <D-S-Space>
map  kcl <D-C-Space>
map! kcl <D-C-Space>
map  lcl <D-C-S-Space>
map! lcl <D-C-S-Space>
map  mcl <D-A-Space>
map! mcl <D-A-Space>
map  ncl <D-A-S-Space>
map! ncl <D-A-S-Space>
map  ocl <D-A-C-Space>
map! ocl <D-A-C-Space>

map  bcm <S-Up>
map! bcm <S-Up>
map  ccm <C-Up>
map! ccm <C-Up>
map  dcm <C-S-Up>
map! dcm <C-S-Up>
map  ecm <A-Up>
map! ecm <A-Up>
map  fcm <A-S-Up>
map! fcm <A-S-Up>
map  gcm <A-C-Up>
map! gcm <A-C-Up>
map  hcm <A-C-S-Up>
map! hcm <A-C-S-Up>
map  jcm <D-S-Up>
map! jcm <D-S-Up>
map  kcm <D-C-Up>
map! kcm <D-C-Up>
map  lcm <D-C-S-Up>
map! lcm <D-C-S-Up>
map  mcm <D-A-Up>
map! mcm <D-A-Up>
map  ncm <D-A-S-Up>
map! ncm <D-A-S-Up>
map  ocm <D-A-C-Up>
map! ocm <D-A-C-Up>

map  bcn <S-Down>
map! bcn <S-Down>
map  ccn <C-Down>
map! ccn <C-Down>
map  dcn <C-S-Down>
map! dcn <C-S-Down>
map  ecn <A-Down>
map! ecn <A-Down>
map  fcn <A-S-Down>
map! fcn <A-S-Down>
map  gcn <A-C-Down>
map! gcn <A-C-Down>
map  hcn <A-C-S-Down>
map! hcn <A-C-S-Down>
map  jcn <D-S-Down>
map! jcn <D-S-Down>
map  kcn <D-C-Down>
map! kcn <D-C-Down>
map  lcn <D-C-S-Down>
map! lcn <D-C-S-Down>
map  mcn <D-A-Down>
map! mcn <D-A-Down>
map  ncn <D-A-S-Down>
map! ncn <D-A-S-Down>
map  ocn <D-A-C-Down>
map! ocn <D-A-C-Down>

map  bco <S-Left>
map! bco <S-Left>
map  cco <C-Left>
map! cco <C-Left>
map  dco <C-S-Left>
map! dco <C-S-Left>
map  eco <A-Left>
map! eco <A-Left>
map  fco <A-S-Left>
map! fco <A-S-Left>
map  gco <A-C-Left>
map! gco <A-C-Left>
map  hco <A-C-S-Left>
map! hco <A-C-S-Left>
map  jco <D-S-Left>
map! jco <D-S-Left>
map  kco <D-C-Left>
map! kco <D-C-Left>
map  lco <D-C-S-Left>
map! lco <D-C-S-Left>
map  mco <D-A-Left>
map! mco <D-A-Left>
map  nco <D-A-S-Left>
map! nco <D-A-S-Left>
map  oco <D-A-C-Left>
map! oco <D-A-C-Left>

map  bcp <S-Right>
map! bcp <S-Right>
map  ccp <C-Right>
map! ccp <C-Right>
map  dcp <C-S-Right>
map! dcp <C-S-Right>
map  ecp <A-Right>
map! ecp <A-Right>
map  fcp <A-S-Right>
map! fcp <A-S-Right>
map  gcp <A-C-Right>
map! gcp <A-C-Right>
map  hcp <A-C-S-Right>
map! hcp <A-C-S-Right>
map  jcp <D-S-Right>
map! jcp <D-S-Right>
map  kcp <D-C-Right>
map! kcp <D-C-Right>
map  lcp <D-C-S-Right>
map! lcp <D-C-S-Right>
map  mcp <D-A-Right>
map! mcp <D-A-Right>
map  ncp <D-A-S-Right>
map! ncp <D-A-S-Right>
map  ocp <D-A-C-Right>
map! ocp <D-A-C-Right>

map  bcq <S-Insert>
map! bcq <S-Insert>
map  ccq <C-Insert>
map! ccq <C-Insert>
map  dcq <C-S-Insert>
map! dcq <C-S-Insert>
map  ecq <A-Insert>
map! ecq <A-Insert>
map  fcq <A-S-Insert>
map! fcq <A-S-Insert>
map  gcq <A-C-Insert>
map! gcq <A-C-Insert>
map  hcq <A-C-S-Insert>
map! hcq <A-C-S-Insert>
map  jcq <D-S-Insert>
map! jcq <D-S-Insert>
map  kcq <D-C-Insert>
map! kcq <D-C-Insert>
map  lcq <D-C-S-Insert>
map! lcq <D-C-S-Insert>
map  mcq <D-A-Insert>
map! mcq <D-A-Insert>
map  ncq <D-A-S-Insert>
map! ncq <D-A-S-Insert>
map  ocq <D-A-C-Insert>
map! ocq <D-A-C-Insert>

map  bcr <S-Delete>
map! bcr <S-Delete>
map  ccr <C-Delete>
map! ccr <C-Delete>
map  dcr <C-S-Delete>
map! dcr <C-S-Delete>
map  ecr <A-Delete>
map! ecr <A-Delete>
map  fcr <A-S-Delete>
map! fcr <A-S-Delete>
map  gcr <A-C-Delete>
map! gcr <A-C-Delete>
map  hcr <A-C-S-Delete>
map! hcr <A-C-S-Delete>
map  jcr <D-S-Delete>
map! jcr <D-S-Delete>
map  kcr <D-C-Delete>
map! kcr <D-C-Delete>
map  lcr <D-C-S-Delete>
map! lcr <D-C-S-Delete>
map  mcr <D-A-Delete>
map! mcr <D-A-Delete>
map  ncr <D-A-S-Delete>
map! ncr <D-A-S-Delete>
map  ocr <D-A-C-Delete>
map! ocr <D-A-C-Delete>

map  bcs <S-Home>
map! bcs <S-Home>
map  ccs <C-Home>
map! ccs <C-Home>
map  dcs <C-S-Home>
map! dcs <C-S-Home>
map  ecs <A-Home>
map! ecs <A-Home>
map  fcs <A-S-Home>
map! fcs <A-S-Home>
map  gcs <A-C-Home>
map! gcs <A-C-Home>
map  hcs <A-C-S-Home>
map! hcs <A-C-S-Home>
map  jcs <D-S-Home>
map! jcs <D-S-Home>
map  kcs <D-C-Home>
map! kcs <D-C-Home>
map  lcs <D-C-S-Home>
map! lcs <D-C-S-Home>
map  mcs <D-A-Home>
map! mcs <D-A-Home>
map  ncs <D-A-S-Home>
map! ncs <D-A-S-Home>
map  ocs <D-A-C-Home>
map! ocs <D-A-C-Home>

map  bct <S-End>
map! bct <S-End>
map  cct <C-End>
map! cct <C-End>
map  dct <C-S-End>
map! dct <C-S-End>
map  ect <A-End>
map! ect <A-End>
map  fct <A-S-End>
map! fct <A-S-End>
map  gct <A-C-End>
map! gct <A-C-End>
map  hct <A-C-S-End>
map! hct <A-C-S-End>
map  jct <D-S-End>
map! jct <D-S-End>
map  kct <D-C-End>
map! kct <D-C-End>
map  lct <D-C-S-End>
map! lct <D-C-S-End>
map  mct <D-A-End>
map! mct <D-A-End>
map  nct <D-A-S-End>
map! nct <D-A-S-End>
map  oct <D-A-C-End>
map! oct <D-A-C-End>

map  bcu <S-PageUp>
map! bcu <S-PageUp>
map  ccu <C-PageUp>
map! ccu <C-PageUp>
map  dcu <C-S-PageUp>
map! dcu <C-S-PageUp>
map  ecu <A-PageUp>
map! ecu <A-PageUp>
map  fcu <A-S-PageUp>
map! fcu <A-S-PageUp>
map  gcu <A-C-PageUp>
map! gcu <A-C-PageUp>
map  hcu <A-C-S-PageUp>
map! hcu <A-C-S-PageUp>
map  jcu <D-S-PageUp>
map! jcu <D-S-PageUp>
map  kcu <D-C-PageUp>
map! kcu <D-C-PageUp>
map  lcu <D-C-S-PageUp>
map! lcu <D-C-S-PageUp>
map  mcu <D-A-PageUp>
map! mcu <D-A-PageUp>
map  ncu <D-A-S-PageUp>
map! ncu <D-A-S-PageUp>
map  ocu <D-A-C-PageUp>
map! ocu <D-A-C-PageUp>

map  bcv <S-PageDown>
map! bcv <S-PageDown>
map  ccv <C-PageDown>
map! ccv <C-PageDown>
map  dcv <C-S-PageDown>
map! dcv <C-S-PageDown>
map  ecv <A-PageDown>
map! ecv <A-PageDown>
map  fcv <A-S-PageDown>
map! fcv <A-S-PageDown>
map  gcv <A-C-PageDown>
map! gcv <A-C-PageDown>
map  hcv <A-C-S-PageDown>
map! hcv <A-C-S-PageDown>
map  jcv <D-S-PageDown>
map! jcv <D-S-PageDown>
map  kcv <D-C-PageDown>
map! kcv <D-C-PageDown>
map  lcv <D-C-S-PageDown>
map! lcv <D-C-S-PageDown>
map  mcv <D-A-PageDown>
map! mcv <D-A-PageDown>
map  ncv <D-A-S-PageDown>
map! ncv <D-A-S-PageDown>
map  ocv <D-A-C-PageDown>
map! ocv <D-A-C-PageDown>
