#!/usr/bin/env bash

is_dead_link() {
  [[ -L "$1" ]] && [[ ! -e "$(readlink "$1")" ]]
}

is_wrong_link() {
  [[ -L "$1" ]] && [[ "$(readlink "$1")" != "$2" ]]
}

is_correct_link() {
  [[ -L "$1" ]] && [[ "$(readlink "$1")" == "$2" ]]
}

exists_but_not_link() {
  [[ -e "$1" ]] && [[ ! -L "$1" ]]
}

make_link() {
  is_correct_link "$2" "$1" && return
  is_dead_link "$2" && rm -f "$2"
  is_wrong_link "$2" "$1" && rm -f "$2"

  # the reason why this needs so much attention, is that
  # if .config/nvim exists and is a directory,
  # ln .vim .config/nvim will create a link '.vim' in .config/nvim

  if exists_but_not_link "$2"; then
    echo "cannot create link "$2", already exists" >&2
  fi

  ln -s "$1" "$2"
}

if [[ "$PWD" != "$HOME/.vim" ]]; then
  echo "$PWD should be $HOME/.vim, move it!" >&2
  exit 1
fi


make_link "$HOME/.vim/init.vim" "$HOME/.vimrc"
mkdir -p "$HOME/.config"
make_link "$HOME/.vim" "$HOME/.config/nvim"


